# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'param.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1257, 886)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 611, 871))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(0, 18, 141, 841))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_6.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_6.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_6.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_6.addWidget(self.label_10)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.label_21 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_6.addWidget(self.label_21)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(320, 18, 281, 841))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_54 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_54.setObjectName("label_54")
        self.verticalLayout_8.addWidget(self.label_54)
        self.bandwidth_Edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.bandwidth_Edit.setObjectName("bandwidth_Edit")
        self.verticalLayout_8.addWidget(self.bandwidth_Edit)
        self.label_55 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_55.setObjectName("label_55")
        self.verticalLayout_8.addWidget(self.label_55)
        self.noisePowerDensity_Edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.noisePowerDensity_Edit.setObjectName("noisePowerDensity_Edit")
        self.verticalLayout_8.addWidget(self.noisePowerDensity_Edit)
        self.label_56 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_56.setObjectName("label_56")
        self.verticalLayout_8.addWidget(self.label_56)
        self.serverSpeed_Edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.serverSpeed_Edit.setObjectName("serverSpeed_Edit")
        self.verticalLayout_8.addWidget(self.serverSpeed_Edit)
        self.label_57 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_57.setObjectName("label_57")
        self.verticalLayout_8.addWidget(self.label_57)
        self.localSpeed_Edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.localSpeed_Edit.setObjectName("localSpeed_Edit")
        self.verticalLayout_8.addWidget(self.localSpeed_Edit)
        self.label_58 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_58.setObjectName("label_58")
        self.verticalLayout_8.addWidget(self.label_58)
        self.powerBudget_Edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.powerBudget_Edit.setObjectName("powerBudget_Edit")
        self.verticalLayout_8.addWidget(self.powerBudget_Edit)
        self.label_59 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_59.setObjectName("label_59")
        self.verticalLayout_8.addWidget(self.label_59)
        self.architectureFactor_Edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.architectureFactor_Edit.setObjectName("architectureFactor_Edit")
        self.verticalLayout_8.addWidget(self.architectureFactor_Edit)
        self.label_60 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_60.setObjectName("label_60")
        self.verticalLayout_8.addWidget(self.label_60)
        self.TasksNumber_Edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.TasksNumber_Edit.setObjectName("TasksNumber_Edit")
        self.verticalLayout_8.addWidget(self.TasksNumber_Edit)
        self.label_61 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_61.setObjectName("label_61")
        self.verticalLayout_8.addWidget(self.label_61)
        self.userNumber_Edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.userNumber_Edit.setObjectName("userNumber_Edit")
        self.verticalLayout_8.addWidget(self.userNumber_Edit)
        self.label_62 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_62.setObjectName("label_62")
        self.verticalLayout_8.addWidget(self.label_62)
        self.GenerateButton = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.GenerateButton.setObjectName("GenerateButton")
        self.verticalLayout_8.addWidget(self.GenerateButton)
        self.label_63 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_63.setObjectName("label_63")
        self.verticalLayout_8.addWidget(self.label_63)
        self.sTotal_Edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.sTotal_Edit.setObjectName("sTotal_Edit")
        self.verticalLayout_8.addWidget(self.sTotal_Edit)
        self.label_64 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_64.setObjectName("label_64")
        self.verticalLayout_8.addWidget(self.label_64)
        self.timeMax_Edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.timeMax_Edit.setObjectName("timeMax_Edit")
        self.verticalLayout_8.addWidget(self.timeMax_Edit)
        self.baseStationGain_value = QtWidgets.QLabel(self.groupBox)
        self.baseStationGain_value.setGeometry(QtCore.QRect(0, 700, 601, 41))
        self.baseStationGain_value.setText("")
        self.baseStationGain_value.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.baseStationGain_value.setObjectName("baseStationGain_value")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(150, 20, 164, 841))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.bandwidth_value = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.bandwidth_value.setText("")
        self.bandwidth_value.setObjectName("bandwidth_value")
        self.verticalLayout_7.addWidget(self.bandwidth_value)
        self.noisePowerDensity_value = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.noisePowerDensity_value.setText("")
        self.noisePowerDensity_value.setObjectName("noisePowerDensity_value")
        self.verticalLayout_7.addWidget(self.noisePowerDensity_value)
        self.serverSpeed_value = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.serverSpeed_value.setText("")
        self.serverSpeed_value.setObjectName("serverSpeed_value")
        self.verticalLayout_7.addWidget(self.serverSpeed_value)
        self.localSpeed_value = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.localSpeed_value.setText("")
        self.localSpeed_value.setObjectName("localSpeed_value")
        self.verticalLayout_7.addWidget(self.localSpeed_value)
        self.powerBudget_value = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.powerBudget_value.setText("")
        self.powerBudget_value.setObjectName("powerBudget_value")
        self.verticalLayout_7.addWidget(self.powerBudget_value)
        self.architectureFactor_value = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.architectureFactor_value.setText("")
        self.architectureFactor_value.setObjectName("architectureFactor_value")
        self.verticalLayout_7.addWidget(self.architectureFactor_value)
        self.TasksNumber_value = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.TasksNumber_value.setText("")
        self.TasksNumber_value.setObjectName("TasksNumber_value")
        self.verticalLayout_7.addWidget(self.TasksNumber_value)
        self.userNumber_value = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.userNumber_value.setText("")
        self.userNumber_value.setObjectName("userNumber_value")
        self.verticalLayout_7.addWidget(self.userNumber_value)
        self.baseStationGain1_value = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.baseStationGain1_value.setText("")
        self.baseStationGain1_value.setObjectName("baseStationGain1_value")
        self.verticalLayout_7.addWidget(self.baseStationGain1_value)
        self.sTotal_value = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.sTotal_value.setText("")
        self.sTotal_value.setObjectName("sTotal_value")
        self.verticalLayout_7.addWidget(self.sTotal_value)
        self.timeMax_value = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.timeMax_value.setText("")
        self.timeMax_value.setObjectName("timeMax_value")
        self.verticalLayout_7.addWidget(self.timeMax_value)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(630, 10, 611, 871))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 92, 681))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_3.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_3.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_3.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_3.addWidget(self.label_14)
        self.label_16 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_3.addWidget(self.label_16)
        self.label_17 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_3.addWidget(self.label_17)
        self.label_18 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_3.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_3.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_3.addWidget(self.label_20)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(110, 20, 141, 681))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tmp_value = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.tmp_value.setText("")
        self.tmp_value.setObjectName("tmp_value")
        self.verticalLayout_5.addWidget(self.tmp_value)
        self.tmpMin_value = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.tmpMin_value.setText("")
        self.tmpMin_value.setObjectName("tmpMin_value")
        self.verticalLayout_5.addWidget(self.tmpMin_value)
        self.maxStep_value = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.maxStep_value.setText("")
        self.maxStep_value.setObjectName("maxStep_value")
        self.verticalLayout_5.addWidget(self.maxStep_value)
        self.maxGlobalEP_value = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.maxGlobalEP_value.setText("")
        self.maxGlobalEP_value.setObjectName("maxGlobalEP_value")
        self.verticalLayout_5.addWidget(self.maxGlobalEP_value)
        self.alpha_value = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.alpha_value.setText("")
        self.alpha_value.setObjectName("alpha_value")
        self.verticalLayout_5.addWidget(self.alpha_value)
        self.globalMin_value = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.globalMin_value.setText("")
        self.globalMin_value.setObjectName("globalMin_value")
        self.verticalLayout_5.addWidget(self.globalMin_value)
        self.baseStationNum_value = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.baseStationNum_value.setText("")
        self.baseStationNum_value.setObjectName("baseStationNum_value")
        self.verticalLayout_5.addWidget(self.baseStationNum_value)
        self.allPossible_value = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.allPossible_value.setText("")
        self.allPossible_value.setObjectName("allPossible_value")
        self.verticalLayout_5.addWidget(self.allPossible_value)
        self.nWorkers_value = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.nWorkers_value.setText("")
        self.nWorkers_value.setObjectName("nWorkers_value")
        self.verticalLayout_5.addWidget(self.nWorkers_value)
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(260, 20, 341, 681))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_65 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_65.setObjectName("label_65")
        self.verticalLayout_9.addWidget(self.label_65)
        self.tmp_Edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_7)
        self.tmp_Edit.setObjectName("tmp_Edit")
        self.verticalLayout_9.addWidget(self.tmp_Edit)
        self.label_66 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_66.setObjectName("label_66")
        self.verticalLayout_9.addWidget(self.label_66)
        self.tmpMin_Edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_7)
        self.tmpMin_Edit.setObjectName("tmpMin_Edit")
        self.verticalLayout_9.addWidget(self.tmpMin_Edit)
        self.label_67 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_67.setObjectName("label_67")
        self.verticalLayout_9.addWidget(self.label_67)
        self.maxStep_Edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_7)
        self.maxStep_Edit.setObjectName("maxStep_Edit")
        self.verticalLayout_9.addWidget(self.maxStep_Edit)
        self.label_68 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_68.setObjectName("label_68")
        self.verticalLayout_9.addWidget(self.label_68)
        self.maxGlobalEP_Edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_7)
        self.maxGlobalEP_Edit.setObjectName("maxGlobalEP_Edit")
        self.verticalLayout_9.addWidget(self.maxGlobalEP_Edit)
        self.label_70 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_70.setObjectName("label_70")
        self.verticalLayout_9.addWidget(self.label_70)
        self.alpha_Edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_7)
        self.alpha_Edit.setObjectName("alpha_Edit")
        self.verticalLayout_9.addWidget(self.alpha_Edit)
        self.label_71 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_71.setObjectName("label_71")
        self.verticalLayout_9.addWidget(self.label_71)
        self.globalMin_Edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_7)
        self.globalMin_Edit.setObjectName("globalMin_Edit")
        self.verticalLayout_9.addWidget(self.globalMin_Edit)
        self.label_72 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_72.setObjectName("label_72")
        self.verticalLayout_9.addWidget(self.label_72)
        self.baseStationNum_Edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_7)
        self.baseStationNum_Edit.setObjectName("baseStationNum_Edit")
        self.verticalLayout_9.addWidget(self.baseStationNum_Edit)
        self.label_73 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_73.setObjectName("label_73")
        self.verticalLayout_9.addWidget(self.label_73)
        self.allPossiblechange_value = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.allPossiblechange_value.setText("")
        self.allPossiblechange_value.setAlignment(QtCore.Qt.AlignCenter)
        self.allPossiblechange_value.setObjectName("allPossiblechange_value")
        self.verticalLayout_9.addWidget(self.allPossiblechange_value)
        self.label_74 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_74.setObjectName("label_74")
        self.verticalLayout_9.addWidget(self.label_74)
        self.nWorkers_Edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_7)
        self.nWorkers_Edit.setObjectName("nWorkers_Edit")
        self.verticalLayout_9.addWidget(self.nWorkers_Edit)
        self.SummitButton = QtWidgets.QPushButton(self.groupBox_2)
        self.SummitButton.setGeometry(QtCore.QRect(510, 720, 75, 23))
        self.SummitButton.setObjectName("SummitButton")
        self.OKButton = QtWidgets.QPushButton(self.groupBox_2)
        self.OKButton.setGeometry(QtCore.QRect(510, 800, 75, 23))
        self.OKButton.setObjectName("OKButton")
        self.ResetButton = QtWidgets.QPushButton(self.groupBox_2)
        self.ResetButton.setGeometry(QtCore.QRect(510, 760, 75, 23))
        self.ResetButton.setObjectName("ResetButton")
        self.CancelButton = QtWidgets.QPushButton(self.groupBox_2)
        self.CancelButton.setGeometry(QtCore.QRect(510, 830, 75, 23))
        self.CancelButton.setObjectName("CancelButton")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox_2)
        self.textBrowser.setGeometry(QtCore.QRect(10, 710, 481, 151))
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "CVX PARAM"))
        self.label_3.setText(_translate("Dialog", "Channel bandwidth:"))
        self.label_2.setText(_translate("Dialog", "noisePowerDensity:"))
        self.label_4.setText(_translate("Dialog", "Speed of each server:"))
        self.label_5.setText(_translate("Dialog", "Speed of local device:"))
        self.label_6.setText(_translate("Dialog", "Power budget:"))
        self.label_7.setText(_translate("Dialog", "Architecture factor:"))
        self.label_8.setText(_translate("Dialog", "Tasks Number:"))
        self.label_9.setText(_translate("Dialog", "userNumber:"))
        self.label_10.setText(_translate("Dialog", "baseStationGain:"))
        self.label.setText(_translate("Dialog", "sTotal:"))
        self.label_21.setText(_translate("Dialog", "timeMax:"))
        self.label_54.setText(_translate("Dialog", "Channel bandwidth:"))
        self.label_55.setText(_translate("Dialog", "noisePowerDensity:"))
        self.label_56.setText(_translate("Dialog", "Speed of each server:"))
        self.label_57.setText(_translate("Dialog", "Speed of local device:"))
        self.label_58.setText(_translate("Dialog", "Power budget:"))
        self.label_59.setText(_translate("Dialog", "Architecture factor:"))
        self.label_60.setText(_translate("Dialog", "Tasks Number:"))
        self.label_61.setText(_translate("Dialog", "userNumber:"))
        self.label_62.setText(_translate("Dialog", "baseStationGain:"))
        self.GenerateButton.setText(_translate("Dialog", "Generate"))
        self.label_63.setText(_translate("Dialog", "sTotal:"))
        self.label_64.setText(_translate("Dialog", "timeMax:"))
        self.groupBox_2.setTitle(_translate("Dialog", "SA PARAM"))
        self.label_11.setText(_translate("Dialog", "tmp:"))
        self.label_12.setText(_translate("Dialog", "tmpMin:"))
        self.label_13.setText(_translate("Dialog", "Max_step:"))
        self.label_14.setText(_translate("Dialog", "Max_Global_EP:"))
        self.label_16.setText(_translate("Dialog", "alpha:"))
        self.label_17.setText(_translate("Dialog", "global_Min:"))
        self.label_18.setText(_translate("Dialog", "baseStationNum:"))
        self.label_19.setText(_translate("Dialog", "allPossible:"))
        self.label_20.setText(_translate("Dialog", "N_WORKERS:"))
        self.label_65.setText(_translate("Dialog", "tmp:"))
        self.label_66.setText(_translate("Dialog", "tmpMin:"))
        self.label_67.setText(_translate("Dialog", "Max_step:"))
        self.label_68.setText(_translate("Dialog", "Max_Global_EP:"))
        self.label_70.setText(_translate("Dialog", "alpha:"))
        self.label_71.setText(_translate("Dialog", "global_Min:"))
        self.label_72.setText(_translate("Dialog", "baseStationNum:"))
        self.label_73.setText(_translate("Dialog", "allPossible:"))
        self.label_74.setText(_translate("Dialog", "N_WORKERS:"))
        self.SummitButton.setText(_translate("Dialog", "Summit"))
        self.OKButton.setText(_translate("Dialog", "OK"))
        self.ResetButton.setText(_translate("Dialog", "Reset"))
        self.CancelButton.setText(_translate("Dialog", "Cancel"))
